// <auto-generated />
using System;
using HealthCareEasyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthCareEasyApi.Migrations
{
    [DbContext(typeof(HCEDbContext))]
    partial class HCEDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HealthCareEasyApi.Models.Benhvien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Benhvien_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DichvuId")
                        .HasColumnType("int");

                    b.Property<string>("Giatien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenbenhvien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thongtin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DichvuId");

                    b.ToTable("Benhvien");
                });

            modelBuilder.Entity("HealthCareEasyApi.Models.Dichvu", b =>
                {
                    b.Property<int?>("DichvuId")
                        .HasColumnType("int");

                    b.Property<string>("Tendichvu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DichvuId");

                    b.ToTable("Dichvu");
                });

            modelBuilder.Entity("HealthCareEasyApi.Models.Benhvien", b =>
                {
                    b.HasOne("HealthCareEasyApi.Models.Dichvu", "Dichvu")
                        .WithMany()
                        .HasForeignKey("DichvuId");

                    b.Navigation("Dichvu");
                });
#pragma warning restore 612, 618
        }
    }
}
